### ISSUE TITLE
[PARSE BUG]: include inside enum

### ISSUE THREAD

**Issue by dyitzchaki-roku** [robotpy/cxxheaderparser#92]
### Problem description

Can't include enum defs from a header file.
Trying to parse
```
enum E {
    #include <enumdefs.h>
};
```
results in
```
Exception:
Traceback (most recent call last):

  File "/home/pyodide/cxxheaderparser/parser.py", line 351, in parse
    self._parse_declarations(tok, doxygen)

  File "/home/pyodide/cxxheaderparser/parser.py", line 2617, in _parse_declarations
    and self._maybe_parse_class_enum_decl(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/pyodide/cxxheaderparser/parser.py", line 2730, in _maybe_parse_class_enum_decl
    self._parse_enum_decl(

  File "/home/pyodide/cxxheaderparser/parser.py", line 1124, in _parse_enum_decl
    values = self._parse_enumerator_list()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/pyodide/cxxheaderparser/parser.py", line 1148, in _parse_enumerator_list
    name_tok = self._next_token_must_be("}", "NAME")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/pyodide/cxxheaderparser/parser.py", line 170, in _next_token_must_be
    raise self._parse_error(tok, "' or '".join(tokenTypes))

cxxheaderparser.errors.CxxParseError: unexpected '#include ', expected '}' or 'NAME'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "", line 102, in on_input

  File "/home/pyodide/cxxheaderparser/simple.py", line 345, in parse_string
    parser.parse()

  File "/home/pyodide/cxxheaderparser/parser.py", line 369, in parse
    raise CxxParseError(msg) from e

cxxheaderparser.errors.CxxParseError: :2: parse error evaluating '#include ': unexpected '#include ', expected '}' or 'NAME'
```

### C++ code that can't be parsed correctly (please double-check that https://robotpy.github.io/cxxheaderparser/ has the same error)

```text
enum E {
    #include <enumdefs.h>
};
```

**Comment by virtuald** [comment]
You need to use a C++ preprocessor. See https://cxxheaderparser.readthedocs.io/en/latest/simple.html#cxxheaderparser.options.ParserOptions.preprocessor

**Comment by dyitzchaki-roku** [comment]
Thanks for the prompt response. I do use the pcpp preprocessor, I guess its their bug then?

**Comment by virtuald** [comment]
If you're using pcpp via https://cxxheaderparser.readthedocs.io/en/latest/custom.html#cxxheaderparser.preprocessor.make_pcpp_preprocessor, then

> If missing #include files are encountered, this preprocessor will ignore the error.

You would need to update the include paths to ensure that the preprocessor can find the included file. You could also use one of the system preprocessors, we have gcc/msvc support.

**Comment by dyitzchaki-roku** [comment]
Fixing the include paths solves this, thanks
